[package]
name = "eyra-panic-example"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
libc = { path = "../../eyra", package = "eyra" }

# This is just an example crate, and not part of the c-ward workspace.
[workspace]
