[package]
name = "eyra-example"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
eyra = { path = "../../eyra" }
libc = "0.2.148"

# This is just an example crate, and not part of the c-ward workspace.
[workspace]
