[package]
name = "eyra-optional-example"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# Depend on Eyra... optionally!
eyra = { path = "../../eyra", optional = true }

# This is just an example crate, and not part of the c-ward workspace.
[workspace]
